// 登录页/个人中心页
export const PERSONAL_LOGIN_SUCCESS = "PERSONAL_LOGIN_SUCCESS";
export const PERSONAL_LOGIN_ISLOGIN = "PERSONAL_LOGIN_ISLOGIN";
export const PERSONAL_LOGIN_INFO = "PERSONAL_LOGIN_INFO";

export const CART_ORDERALL = "CART_ORDERALL";
export const CART_UPDATE_SELECT_ALL = "CART_UPDATE_SELECT_ALL";
export const CART_UPDATE_SELECT = "CART_UPDATE_SELECT";
export const CART_UPDATE_SELECT_ALL_EDITE = "CART_UPDATE_SELECT_ALL_EDITE";
export const CART_UPDATE_SELECT_EDITE = "CART_UPDATE_SELECT_EDITE";
export const CART_UPDATE_EDITE = "CART_UPDATE_EDITE";
export const CART_UPDATE_COUNT = "CART_UPDATE_COUNT";
export const CART_REMOVE = "CART_REMOVE";
